"""Regression checks for the Home Assistant custom-panel integration boundary."""

from pathlib import Path
import unittest


ROOT = Path(__file__).parents[1]
PANEL_SOURCE = (ROOT / "custom_components/mise_en_place_assistant/panel.py").read_text()
INIT_SOURCE = (ROOT / "custom_components/mise_en_place_assistant/__init__.py").read_text()
STORE_SOURCE = (ROOT / "custom_components/mise_en_place_assistant/store.py").read_text()
FRONTEND_SOURCE = (ROOT / "custom_components/mise_en_place_assistant/panel_frontend.js").read_text()
M5DIAL_SOURCE = (ROOT / "m5dial/m5dial-mise-en-place-assistant.yaml").read_text()


class TestPanelContract(unittest.TestCase):
    """Keep the sidebar panel on Home Assistant's public custom-panel API."""

    def test_registers_a_local_custom_panel(self) -> None:
        self.assertIn("from homeassistant.components import frontend, panel_custom, websocket_api", PANEL_SOURCE)
        self.assertIn("await panel_custom.async_register_panel(", PANEL_SOURCE)
        self.assertIn("webcomponent_name=PANEL_COMPONENT_NAME", PANEL_SOURCE)
        self.assertIn("module_url=PANEL_MODULE_URL", PANEL_SOURCE)
        self.assertIn("embed_iframe=False", PANEL_SOURCE)
        self.assertIn("trust_external=False", PANEL_SOURCE)
        self.assertIn("Received sidebar overview WebSocket request", PANEL_SOURCE)
        self.assertIn("Could not build sidebar overview response", PANEL_SOURCE)
        self.assertNotIn('"_panel_custom"', PANEL_SOURCE)

    def test_waits_for_panel_registration(self) -> None:
        self.assertIn("await async_register_panel(hass)", INIT_SOURCE)

    def test_mocked_catalog_seeds_bounded_sample_data_on_first_setup(self) -> None:
        self.assertIn("manager.effective_catalog_providers() == [PROVIDER_MOCKED] and not manager.containers", INIT_SOURCE)
        self.assertIn("await manager.async_seed_demo_data()", INIT_SOURCE)
        self.assertIn("async_seed_demo_data", STORE_SOURCE)
        self.assertIn("Demo tag IDs are deliberately stable", STORE_SOURCE)

    def test_locations_are_managed_by_stable_id(self) -> None:
        self.assertIn('VOID_LOCATION_ID = "__void__"', (ROOT / "custom_components/mise_en_place_assistant/const.py").read_text())
        self.assertIn("SERVICE_CREATE_LOCATION", INIT_SOURCE)
        self.assertIn("SERVICE_UPDATE_LOCATION", INIT_SOURCE)
        self.assertIn("SERVICE_DELETE_LOCATION", INIT_SOURCE)
        self.assertIn("SERVICE_MOVE_CONTAINER", INIT_SOURCE)
        self.assertIn("incoming_location_ids", M5DIAL_SOURCE)
        self.assertIn("location_id: !lambda 'return id(selected_location_id);'", M5DIAL_SOURCE)
        self.assertNotIn("incoming_locations", M5DIAL_SOURCE)
        self.assertIn('"location_id": container.get("location_id")', PANEL_SOURCE)
        self.assertIn("storage_locations", STORE_SOURCE)
        self.assertIn("Create storage locations in Grocy", STORE_SOURCE)
        self.assertIn("VOID_LOCATION_NAME", STORE_SOURCE)

    def test_m5dial_workflow_contract_is_request_scoped_and_provider_aware(self) -> None:
        self.assertIn("ATTR_REQUEST_ID", INIT_SOURCE)
        self.assertIn("ATTR_SOURCE_PROVIDER", INIT_SOURCE)
        self.assertIn("request_id", M5DIAL_SOURCE)
        self.assertIn("active_request_id", M5DIAL_SOURCE)
        self.assertIn("id(active_request_id) == request_id", M5DIAL_SOURCE)
        self.assertIn("incoming_item_providers", INIT_SOURCE)
        self.assertIn("incoming_item_content_kinds", INIT_SOURCE)
        self.assertIn("incoming_item_providers", M5DIAL_SOURCE)
        self.assertIn("incoming_item_content_kinds", M5DIAL_SOURCE)
        self.assertIn("source_provider: !lambda 'return id(selected_item_provider);'", M5DIAL_SOURCE)
        self.assertIn("content_kind: !lambda 'return id(selected_content_kind);'", M5DIAL_SOURCE)
        self.assertIn("location: !lambda 'return id(selected_location_label);'", M5DIAL_SOURCE)
        self.assertIn("async_create_recipe_container", INIT_SOURCE)
        self.assertIn("Grocy stock saved", INIT_SOURCE)
        self.assertIn("Mealie prep saved", INIT_SOURCE)
        self.assertIn("result_title", M5DIAL_SOURCE)
        self.assertIn("Physical UX contract", M5DIAL_SOURCE)
        self.assertIn("Short press advances exactly one step", M5DIAL_SOURCE)
        self.assertIn("Long press opens the lightweight Mise listening view", M5DIAL_SOURCE)
        self.assertIn("always-available cancel/idle escape", M5DIAL_SOURCE)
        self.assertIn("Press to exit", M5DIAL_SOURCE)
        self.assertIn("Thinking with Home Assistant", M5DIAL_SOURCE)
        self.assertIn("Checking with Home Assistant", M5DIAL_SOURCE)

    def test_panel_has_location_management_tab(self) -> None:
        self.assertIn("Dashboard", FRONTEND_SOURCE)
        self.assertIn("Inventory", FRONTEND_SOURCE)
        self.assertIn("Storage", FRONTEND_SOURCE)
        self.assertIn("Planning", FRONTEND_SOURCE)
        self.assertIn('["info", "Info"]', FRONTEND_SOURCE)
        self.assertIn("_infoView(data)", FRONTEND_SOURCE)
        self.assertIn("_integrationStatusRow", FRONTEND_SOURCE)
        self.assertIn("_shoppingTargetLabel", FRONTEND_SOURCE)
        self.assertIn("Storage locations", FRONTEND_SOURCE)
        self.assertIn("this._opsStrip(summary, operations, data?.shopping, data?.storage_attention, this._tab)", FRONTEND_SOURCE)
        self.assertIn('activeTab === "storage"', FRONTEND_SOURCE)
        self.assertIn('"update_location"', FRONTEND_SOURCE)
        self.assertIn('"create_location"', FRONTEND_SOURCE)
        self.assertIn('id="add-location"', FRONTEND_SOURCE)
        self.assertIn('id="add-container"', FRONTEND_SOURCE)
        self.assertIn("_selectedLocation", FRONTEND_SOURCE)
        self.assertIn("[data-select-location]", FRONTEND_SOURCE)
        self.assertIn("View containers", FRONTEND_SOURCE)
        self.assertIn('"entities": entity_options', PANEL_SOURCE)
        self.assertIn("def _entity_options", PANEL_SOURCE)
        self.assertIn('domain not in {"binary_sensor", "sensor", "switch"}', PANEL_SOURCE)
        self.assertIn('_entitySelect("temperature", sensors.temperature, ["sensor"])', FRONTEND_SOURCE)
        self.assertIn('_entitySelect("door", sensors.door, ["binary_sensor"])', FRONTEND_SOURCE)
        self.assertIn('_entitySelect("power_switch", sensors.power_switch, ["switch"])', FRONTEND_SOURCE)
        self.assertIn('this._hass.callService("mise_en_place_assistant", "delete_location"', FRONTEND_SOURCE)
        self.assertIn('this._hass.callService("mise_en_place_assistant", "move_container"', FRONTEND_SOURCE)
        self.assertNotIn("Clear metadata", FRONTEND_SOURCE)
        self.assertIn("_locationCard(location, containers, locations", FRONTEND_SOURCE)
        self.assertIn("selected ? this._locationContents(location, containers, locations)", FRONTEND_SOURCE)
        self.assertIn("this._locationContentAttention(location, containers)", FRONTEND_SOURCE)
        self.assertIn('const sublocation = container.sublocation || "Main"', FRONTEND_SOURCE)
        self.assertIn("location-card type-", FRONTEND_SOURCE)
        self.assertIn("location-card-header", FRONTEND_SOURCE)
        self.assertIn("location-card-body", FRONTEND_SOURCE)
        self.assertIn("icon-button", FRONTEND_SOURCE)
        self.assertIn('title="Edit location"', FRONTEND_SOURCE)
        self.assertIn('aria-label="Edit location"', FRONTEND_SOURCE)
        self.assertIn(".location-card.type-fridge", FRONTEND_SOURCE)
        self.assertIn("_cssToken(locationType)", FRONTEND_SOURCE)
        self.assertIn('"area_icon": getattr(area, "icon", None) if area else None', PANEL_SOURCE)
        self.assertIn("_locationArea(location)", FRONTEND_SOURCE)
        self.assertIn("_locationTypeIcon(locationType)", FRONTEND_SOURCE)
        self.assertIn("mdi:floor-plan", FRONTEND_SOURCE)

    def test_storage_locations_support_sublocations(self) -> None:
        self.assertIn('"sublocations": annotation.get("sublocations", [])', STORE_SOURCE)
        self.assertIn("def resolve_sublocation", STORE_SOURCE)
        self.assertIn('"sublocation": container.get("sublocation") or ""', PANEL_SOURCE)
        self.assertIn('name="sublocations"', FRONTEND_SOURCE)
        self.assertIn('name="sublocation"', FRONTEND_SOURCE)
        self.assertIn('this._placeLabel(container)', FRONTEND_SOURCE)
        self.assertIn("container-name", FRONTEND_SOURCE)
        self.assertIn("container-card", FRONTEND_SOURCE)
        self.assertIn("container-titleline", FRONTEND_SOURCE)
        self.assertIn("_contentKindChip(kind)", FRONTEND_SOURCE)
        self.assertIn("_contentKindIcon(kind)", FRONTEND_SOURCE)
        self.assertIn("_placeChip(item)", FRONTEND_SOURCE)
        self.assertIn("_containerAttention(item)", FRONTEND_SOURCE)
        self.assertIn("attention-chip", FRONTEND_SOURCE)
        self.assertIn("Low stock", FRONTEND_SOURCE)
        self.assertIn("Past best before", FRONTEND_SOURCE)
        self.assertIn("1 item needs attention", FRONTEND_SOURCE)
        self.assertIn('title="Move container"', FRONTEND_SOURCE)
        self.assertIn('aria-label="Clear container"', FRONTEND_SOURCE)
        self.assertIn("mdi:map-marker-outline", FRONTEND_SOURCE)
        self.assertIn("ATTR_SUBLOCATION", INIT_SOURCE)
        self.assertIn("ATTR_SUBLOCATIONS", INIT_SOURCE)

    def test_panel_has_dev_tab_for_live_testing(self) -> None:
        self.assertIn('["dev", "Dev"]', FRONTEND_SOURCE)
        self.assertIn("_devView(data)", FRONTEND_SOURCE)
        self.assertIn("Dev controls", FRONTEND_SOURCE)
        self.assertIn("Copy overview JSON", FRONTEND_SOURCE)
        self.assertIn("Simulate CRUD", FRONTEND_SOURCE)
        self.assertIn('"simulate_crud"', FRONTEND_SOURCE)
        self.assertIn("SERVICE_SIMULATE_CRUD", INIT_SOURCE)
        self.assertIn("_loadIfNoEventSocket", FRONTEND_SOURCE)
        self.assertIn("Queue Grocy minimum stock", FRONTEND_SOURCE)

    def test_panel_surfaces_shopping_workflow_status(self) -> None:
        self.assertIn("shopping_status = manager.shopping_workflow_status()", PANEL_SOURCE)
        self.assertIn('"shopping": shopping_status', PANEL_SOURCE)
        self.assertIn('"operations": {', PANEL_SOURCE)
        self.assertIn('"catalog_providers": manager.effective_catalog_providers()', PANEL_SOURCE)
        self.assertIn('float(container.get("canonical_quantity", container.get("quantity", 0))) <= 2', PANEL_SOURCE)
        self.assertIn("Shopping workflow", FRONTEND_SOURCE)
        self.assertIn("Add shopping item", FRONTEND_SOURCE)
        self.assertIn("add_to_shopping_list", FRONTEND_SOURCE)
        self.assertIn("add_empty_containers_to_shopping_list", FRONTEND_SOURCE)
        self.assertIn("add_missing_products_to_shopping_list", FRONTEND_SOURCE)
        self.assertIn("data-queue-empty-containers", FRONTEND_SOURCE)
        self.assertIn("data-queue-product", FRONTEND_SOURCE)
        self.assertIn("Queue missing prep", FRONTEND_SOURCE)
        self.assertIn("missing_prep_item", FRONTEND_SOURCE)
        self.assertIn("data-sync-missing-products", FRONTEND_SOURCE)
        self.assertNotIn('id="queue-empty-containers"', FRONTEND_SOURCE)
        self.assertNotIn('id="sync-missing-products"', FRONTEND_SOURCE)
        self.assertNotIn("sync_grocy_products_to_mealie", FRONTEND_SOURCE)
        self.assertNotIn("grocy_mealie_food_sync", STORE_SOURCE)

    def test_panel_surfaces_readiness_signals(self) -> None:
        self.assertIn('"readiness": readiness', PANEL_SOURCE)
        self.assertIn('"planning_comparison": planning_comparison', PANEL_SOURCE)
        self.assertIn('"suggested_actions": suggested_actions', PANEL_SOURCE)
        self.assertIn("def _suggested_actions_data", PANEL_SOURCE)
        self.assertIn("def _suggested_action", PANEL_SOURCE)
        self.assertIn("def _suggested_action_sort_key", PANEL_SOURCE)
        self.assertIn("def _shopping_target_label", PANEL_SOURCE)
        self.assertIn("def _shopping_target_summary", PANEL_SOURCE)
        self.assertIn("def _latest_shopping_log", PANEL_SOURCE)
        self.assertIn("def _minimum_stock_reason", PANEL_SOURCE)
        self.assertIn("def _product_attention_reason", PANEL_SOURCE)
        self.assertIn("def _freshness_reason", PANEL_SOURCE)
        self.assertIn("def _storage_attention_reason", PANEL_SOURCE)
        self.assertIn("def _sample_names", PANEL_SOURCE)
        self.assertIn("reason=zero_recipe_container", PANEL_SOURCE)
        self.assertIn("reason=missing_prep_item", PANEL_SOURCE)
        self.assertIn('"sources": sources or []', PANEL_SOURCE)
        self.assertIn('"target": target or ""', PANEL_SOURCE)
        self.assertIn('"last_queued": last_queued or None', PANEL_SOURCE)
        self.assertIn("empty_container_refill", PANEL_SOURCE)
        self.assertIn("grocy_minimum_stock", PANEL_SOURCE)
        self.assertIn("explicit_shopping_request", PANEL_SOURCE)
        self.assertIn("has no stock because", PANEL_SOURCE)
        self.assertIn("expires", PANEL_SOURCE)
        self.assertIn("was opened", PANEL_SOURCE)
        self.assertIn("needs a location", PANEL_SOURCE)
        self.assertIn('"payload": payload or {}', PANEL_SOURCE)
        self.assertIn('sources=["Grocy stock"]', PANEL_SOURCE)
        self.assertIn('sources=["Mise container"]', PANEL_SOURCE)
        self.assertIn('sources=["Location health", "Mise container"]', PANEL_SOURCE)
        self.assertIn('"storage_attention": storage_attention', PANEL_SOURCE)
        self.assertIn("storage_attention_summary", PANEL_SOURCE)
        self.assertIn("critical_locations", STORE_SOURCE)
        self.assertIn("warning_locations", STORE_SOURCE)
        self.assertIn("status_label", STORE_SOURCE)
        self.assertIn("_storage_status_label", STORE_SOURCE)
        self.assertIn("def _readiness_data", PANEL_SOURCE)
        self.assertIn("def _planning_comparison_data", PANEL_SOURCE)
        self.assertIn("def _related_log", PANEL_SOURCE)
        self.assertIn("def _recipe_summary", PANEL_SOURCE)
        self.assertIn("def _enriched_item_totals", PANEL_SOURCE)
        self.assertIn('"physical_containers"', PANEL_SOURCE)
        self.assertIn('"freshness_dates"', PANEL_SOURCE)
        self.assertIn('"last_stock_log"', PANEL_SOURCE)
        self.assertIn('"recipe": _recipe_summary', PANEL_SOURCE)
        self.assertIn('"tags": recipe.get("tags")', PANEL_SOURCE)
        self.assertIn('"categories": recipe.get("categories")', PANEL_SOURCE)
        self.assertIn('container.get("content_kind") != "recipe"', PANEL_SOURCE)
        self.assertIn('"ready": len(readiness["ready"])', PANEL_SOURCE)
        self.assertIn('"location_at_risk": len(readiness["location_at_risk"])', PANEL_SOURCE)
        self.assertIn("Grocy-backed product has stock", PANEL_SOURCE)
        self.assertIn("Prepared component exists in Mise inventory", PANEL_SOURCE)
        self.assertIn("Container needs a storage location", PANEL_SOURCE)
        self.assertIn("Prepared components vs Grocy stock", FRONTEND_SOURCE)
        self.assertIn("Last stock write", FRONTEND_SOURCE)
        self.assertIn("Grocy stock", FRONTEND_SOURCE)
        self.assertIn("_planningComparisonRow", FRONTEND_SOURCE)
        self.assertIn("Location at risk", FRONTEND_SOURCE)
        self.assertIn("_readinessPanel(readiness", FRONTEND_SOURCE)
        self.assertIn("Latest provider note", FRONTEND_SOURCE)
        self.assertIn("minimum stock available", FRONTEND_SOURCE)
        self.assertIn("Storage attention needed", FRONTEND_SOURCE)
        self.assertIn("Storage attention critical", FRONTEND_SOURCE)
        self.assertIn("Storage automation clear", FRONTEND_SOURCE)
        self.assertNotIn("Storage monitoring not configured", FRONTEND_SOURCE)
        self.assertIn("Storage monitoring unavailable", FRONTEND_SOURCE)
        self.assertIn("_locationMonitoring(health, readings)", FRONTEND_SOURCE)
        self.assertIn('health.status === "not_configured"', FRONTEND_SOURCE)
        self.assertIn('ha-icon icon="${icon}"', FRONTEND_SOURCE)
        self.assertIn("_storageAttentionSummary", FRONTEND_SOURCE)
        self.assertIn("_storageStatusLabel", FRONTEND_SOURCE)
        self.assertIn("Next actions", FRONTEND_SOURCE)
        self.assertIn("Suggested next actions", FRONTEND_SOURCE)
        self.assertIn("_dashboardActionContext(readiness", FRONTEND_SOURCE)
        self.assertIn("_suggestedActionsPanel", FRONTEND_SOURCE)
        self.assertIn("_suggestedActionLabel", FRONTEND_SOURCE)
        self.assertIn("_summaryRow", FRONTEND_SOURCE)
        self.assertIn("Queue shopping", FRONTEND_SOURCE)
        self.assertIn("Target:", FRONTEND_SOURCE)
        self.assertIn("Last queued:", FRONTEND_SOURCE)
        self.assertIn("_shoppingLogSummary", FRONTEND_SOURCE)
        self.assertIn("Open review", FRONTEND_SOURCE)
        self.assertIn("Add quantity", FRONTEND_SOURCE)
        self.assertIn("Remove quantity", FRONTEND_SOURCE)
        self.assertIn("Clear container", FRONTEND_SOURCE)
        self.assertIn("Archive container", FRONTEND_SOURCE)
        self.assertIn("Move...", FRONTEND_SOURCE)
        self.assertIn('title="Move container"', FRONTEND_SOURCE)
        self.assertIn("action.sources", FRONTEND_SOURCE)
        self.assertIn("data-suggested-service", FRONTEND_SOURCE)
        self.assertIn("data-suggested-tab", FRONTEND_SOURCE)
        self.assertIn("_runSuggestedService", FRONTEND_SOURCE)

    def test_panel_exposes_container_lifecycle_actions(self) -> None:
        self.assertIn("fill_container", FRONTEND_SOURCE)
        self.assertIn("remove_items", FRONTEND_SOURCE)
        self.assertIn("clear_container", FRONTEND_SOURCE)
        self.assertIn("archive_container", FRONTEND_SOURCE)
        self.assertIn("restore_container", FRONTEND_SOURCE)
        self.assertIn("Archived containers", FRONTEND_SOURCE)
        self.assertIn("this._quantityNumber(container) === 0", FRONTEND_SOURCE)
        self.assertIn("_applyBusyState", FRONTEND_SOURCE)
        self.assertIn("_withBusy", FRONTEND_SOURCE)

    def test_panel_surfaces_product_attention_metadata(self) -> None:
        self.assertIn('"product_attention": product_attention', PANEL_SOURCE)
        self.assertIn("product_metadata", STORE_SOURCE)
        self.assertIn("product_attention_items", STORE_SOURCE)
        self.assertIn("PROVIDER_MOCKED", STORE_SOURCE)
        self.assertIn("async_update_product_metadata", STORE_SOURCE)
        self.assertIn("SERVICE_UPDATE_PRODUCT_METADATA", INIT_SOURCE)
        self.assertIn("update_product_metadata", FRONTEND_SOURCE)
        self.assertIn("Container policy", FRONTEND_SOURCE)
        self.assertIn("Expected storage", FRONTEND_SOURCE)
        self.assertIn("Staple / par-managed", FRONTEND_SOURCE)
        self.assertIn("available_in_mealie", STORE_SOURCE)
        self.assertIn("Available in Mealie", FRONTEND_SOURCE)
        self.assertIn("meal_role", STORE_SOURCE)


if __name__ == "__main__":
    unittest.main()
